name: Terraform

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  terraform:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt

      - name: Package Lambda
        run: |
          cd lambda
          zip -r ../lambda.zip .

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Plan
        run: terraform -chdir=terraform plan

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve
